/*     */ package me.thediamondsword5.moloch.module.modules.client;@Parallel
/*     */ @ModuleInfo(name = "MoreClickGUI", category = Category.CLIENT, description = "I ran out of fucking space in clickgui it won't compile")
/*     */ public class MoreClickGUI extends Module { public static MoreClickGUI instance; Setting<Page> page; public Setting<DescriptionMode> descriptionMode; public Setting<Boolean> descriptionModeHubExpandUp; public Setting<DescriptionModeHubPage> descriptionModeHubPage; public Setting<Integer> descriptionModeHubLength; public Setting<Integer> descriptionModeHubInitialHeight; public Setting<Integer> descriptionModeHubHeightBetweenRowsOfText; public Setting<Boolean> descriptionModeHubRounded; public Setting<Float> descriptionModeHubRoundedRadius; public Setting<Boolean> descriptionModeHubRoundedTopRight; public Setting<Boolean> descriptionModeHubRoundedTopLeft; public Setting<Boolean> descriptionModeHubRoundedBottomRight; public Setting<Boolean> descriptionModeHubRoundedBottomLeft; public Setting<Boolean> descriptionModeHubAnimation; public Setting<Float> descriptionModeHubAnimationSpeed; public Setting<Color> descriptionModeHubColor; public Setting<Boolean> descriptionModeHubOutline; public Setting<Float> descriptionModeHubOutlineWidth; public Setting<Color> descriptionModeHubOutlineColor; public Setting<Boolean> descriptionModeHubHeaderText; public Setting<DescriptionModeHubDesTextFont> descriptionModeHubDesTextFont; public Setting<Boolean> descriptionModeHubDesTextShadow;
/*     */   public Setting<Float> descriptionModeHubHeaderTextSize;
/*     */   public Setting<Integer> descriptionModeHubHeaderTextXOffset;
/*     */   public Setting<Integer> descriptionModeHubHeaderTextYOffset;
/*     */   public Setting<Color> descriptionModeHubHeaderTextColor;
/*     */   public Setting<Boolean> descriptionModeHubIcon;
/*     */   public Setting<Float> descriptionModeHubIconSize;
/*     */   public Setting<Integer> descriptionModeHubIconXOffset;
/*     */   public Setting<Integer> descriptionModeHubIconYOffset;
/*     */   public Setting<Color> descriptionModeHubIconColor;
/*     */   public Setting<DescriptionModeHubDesTextFont> descriptionModeHubDescriptionFont;
/*     */   public Setting<Boolean> descriptionModeHubDescriptionShadow;
/*     */   public Setting<Float> descriptionModeHubDescriptionSize;
/*     */   public Setting<Boolean> descriptionModeHubDescriptionAnimation;
/*     */   
/*     */   public MoreClickGUI() {
/*  19 */     this.page = setting("Page", Page.Description);
/*     */     
/*  21 */     this.descriptionMode = setting("DescriptionMode", DescriptionMode.Hub).des("Description Mode").whenAtMode(this.page, Page.Description);
/*  22 */     this.descriptionModeHubExpandUp = setting("DesHubExpandUp", false).des("Description Mode Hub Expand Upwards").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.page, Page.Description);
/*  23 */     this.descriptionModeHubPage = setting("DescriptionHubPage", DescriptionModeHubPage.Bar).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.page, Page.Description);
/*  24 */     this.descriptionModeHubLength = setting("DescriptionHubLength", 149, 20, 300).des("Description Mode Hub Length").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  25 */     this.descriptionModeHubInitialHeight = setting("DesHubStartHeight", 34, 0, 100).des("Description Mode Hub Initial Height").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  26 */     this.descriptionModeHubHeightBetweenRowsOfText = setting("DesHubRowHeight", 1, 0, 10).des("Description Mode Hub Height Between Rows Of Text").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  27 */     this.descriptionModeHubRounded = setting("DescriptionHubRound", false).des("Description Mode Hub Rounded").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  28 */     this.descriptionModeHubRoundedRadius = setting("DesHubCornerRadius", 0.5F, 0.0F, 1.0F).des("Description Mode Hub Rounded Corner Radius").whenTrue(this.descriptionModeHubRounded).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  29 */     this.descriptionModeHubRoundedTopRight = setting("DesHubRoundedTopRight", true).des("Description Mode Hub Rounded Top Right").whenTrue(this.descriptionModeHubRounded).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  30 */     this.descriptionModeHubRoundedTopLeft = setting("DesHubRoundedTopLeft", true).des("Description Mode Hub Rounded Top Left").whenTrue(this.descriptionModeHubRounded).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  31 */     this.descriptionModeHubRoundedBottomRight = setting("DesHubRoundedDownRight", true).des("Description Mode Hub Rounded Bottom Right").whenTrue(this.descriptionModeHubRounded).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  32 */     this.descriptionModeHubRoundedBottomLeft = setting("DesHubRoundedDownLeft", true).des("Description Mode Hub Rounded Bottom Left").whenTrue(this.descriptionModeHubRounded).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  33 */     this.descriptionModeHubAnimation = setting("DescriptionHubAnimate", true).des("Description Mode Hub Animate On Height Difference").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  34 */     this.descriptionModeHubAnimationSpeed = setting("DesHubAnimateSpeed", 8.0F, 1.0F, 10.0F).des("Description Mode Hub Animate On Height Difference Speed").whenTrue(this.descriptionModeHubAnimation).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  35 */     this.descriptionModeHubColor = setting("DesHubColor", new Color((new Color(0, 0, 0, 168)).getRGB(), false, false, 1.0F, 0.75F, 0.9F, 0, 0, 0, 168)).des("Description Mode Hub Color").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Rect).whenAtMode(this.page, Page.Description);
/*  36 */     this.descriptionModeHubOutline = setting("DesHubOutline", false).des("Description Mode Hub Outline").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(this.page, Page.Description);
/*  37 */     this.descriptionModeHubOutlineWidth = setting("DesHubOutlineWidth", 1.0F, 1.0F, 2.0F).des("Description Mode Hub Outline Width").whenTrue(this.descriptionModeHubOutline).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(this.page, Page.Description);
/*  38 */     this.descriptionModeHubOutlineColor = setting("DesHubOutlineColor", new Color((new Color(120, 40, 255, 255)).getRGB(), false, false, 1.0F, 0.75F, 0.9F, 120, 40, 255, 255)).des("Description Mode Hub Outline Color").whenTrue(this.descriptionModeHubOutline).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Outline).whenAtMode(this.page, Page.Description);
/*     */     
/*  40 */     this.descriptionModeHubHeaderText = setting("DesHubHeadText", true).des("Description Mode Hub 'Description' Text").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  41 */     this.descriptionModeHubDesTextFont = setting("DesHubHeadTextFont", DescriptionModeHubDesTextFont.Objectivity).des("Description Mode Hub 'Description' Text Font").whenTrue(this.descriptionModeHubHeaderText).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  42 */     this.descriptionModeHubDesTextShadow = setting("DesHubHeadTextShadow", false).des("Description Mode Hub 'Description' Text Shadow").whenTrue(this.descriptionModeHubHeaderText).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  43 */     this.descriptionModeHubHeaderTextSize = setting("DesHubHeadTextSize", 1.0F, 0.1F, 3.0F).des("Description Mode Hub 'Description' Text Size").whenTrue(this.descriptionModeHubHeaderText).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  44 */     this.descriptionModeHubHeaderTextXOffset = setting("DesHubHeadTextX", 39, -50, 50).des("Description Mode Hub 'Description' Text X Offset").whenTrue(this.descriptionModeHubHeaderText).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  45 */     this.descriptionModeHubHeaderTextYOffset = setting("DesHubHeadTextY", 1, -50, 50).des("Description Mode Hub 'Description' Text Y Offset").whenTrue(this.descriptionModeHubHeaderText).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  46 */     this.descriptionModeHubHeaderTextColor = setting("DesHubHeadTextColor", new Color((new Color(255, 255, 255, 255)).getRGB(), false, false, 1.0F, 0.75F, 0.9F, 255, 255, 255, 255)).des("Description Mode Hub 'Description' Text Color").whenTrue(this.descriptionModeHubHeaderText).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  47 */     this.descriptionModeHubIcon = setting("DescriptionHubIcon", true).des("Description Mode Hub Icon").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  48 */     this.descriptionModeHubIconSize = setting("DesHubIconSize", 0.9F, 0.1F, 3.0F).des("Description Mode Hub Icon Size").whenTrue(this.descriptionModeHubIcon).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  49 */     this.descriptionModeHubIconXOffset = setting("DesHubIconX", 5, -50, 50).des("Description Mode Hub Icon X Offset").whenTrue(this.descriptionModeHubIcon).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  50 */     this.descriptionModeHubIconYOffset = setting("DesHubIconY", -1, -50, 50).des("Description Mode Hub Icon Y Offset").whenTrue(this.descriptionModeHubIcon).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  51 */     this.descriptionModeHubIconColor = setting("DesHubIconColor", new Color((new Color(255, 255, 255, 200)).getRGB(), false, false, 1.0F, 0.75F, 0.9F, 255, 255, 255, 200)).des("Description Mode Hub Icon Color").whenTrue(this.descriptionModeHubIcon).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  52 */     this.descriptionModeHubDescriptionFont = setting("DesHubDesTextFont", DescriptionModeHubDesTextFont.Comfortaa).des("Description Mode Hub Description Text Font").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  53 */     this.descriptionModeHubDescriptionShadow = setting("DesHubDesTextShadow", false).des("Description Mode Hub Description Text Shadow").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  54 */     this.descriptionModeHubDescriptionSize = setting("DesHubDesTextSize", 1.0F, 0.1F, 3.0F).des("Description Mode Hub Size Of Description Text").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  55 */     this.descriptionModeHubDescriptionAnimation = setting("DesHubDesAnimation", true).des("Description Mode Hub Description Text Animation On Change Text").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  56 */     this.descriptionModeHubDescriptionAnimationSpeed = setting("DesHubDesAnimateSpeed", 4.0F, 1.0F, 10.0F).des("Description Mode Hub Description Text Animation On Change Text Speed").whenTrue(this.descriptionModeHubDescriptionAnimation).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  57 */     this.descriptionModeHubDescriptionXOffset = setting("DesHubDesTextX", 4, 0, 50).des("Description Mode Hub Description Text X Offset").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  58 */     this.descriptionModeHubDescriptionXBoundingOffset = setting("DesHubDesTextFarX", 4, 0, 50).des("Description Mode Hub Description Text X Ending Offset").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  59 */     this.descriptionModeHubDescriptionYOffset = setting("DesHubDesTextY", 7, -30, 30).des("Description Mode Hub Description Text Y Offset").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*  60 */     this.descriptionModeHubDescriptionColor = setting("DesHubDesTextColor", new Color((new Color(200, 200, 200, 200)).getRGB(), false, false, 1.0F, 0.75F, 0.9F, 200, 200, 200, 200)).des("Description Mode Hub Description Text Color").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Text).whenAtMode(this.page, Page.Description);
/*     */     
/*  62 */     this.descriptionModeHubShadow = setting("DescriptionHubShadow", true).des("Description Mode Hub Gradient Shadow").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Shadow).whenAtMode(this.page, Page.Description);
/*  63 */     this.descriptionModeHubShadowCenterRect = setting("DesHubShadowCenterRect", false).des("Description Mode Hub Gradient Shadow Center Rect").whenTrue(this.descriptionModeHubShadow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Shadow).whenAtMode(this.page, Page.Description);
/*  64 */     this.descriptionModeHubShadowSize = setting("DesHubShadowSize", 0.1F, 0.0F, 1.0F).des("Description Mode Hub Gradient Shadow Size").whenTrue(this.descriptionModeHubShadow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Shadow).whenAtMode(this.page, Page.Description);
/*  65 */     this.descriptionModeHubShadowAlpha = setting("DesHubShadowAlpha", 129, 0, 255).des("Description Mode Hub Gradient Shadow Alpha").whenTrue(this.descriptionModeHubShadow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Shadow).whenAtMode(this.page, Page.Description);
/*     */     
/*  67 */     this.descriptionModeHubBar = setting("DescriptionHubBar", true).des("Description Mode Hub Color Bar").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub)).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  68 */     this.descriptionModeHubBarPage = setting("DesHubBarPage", DescriptionModeHubBarPage.Glow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  69 */     this.descriptionModeHubBarHeight = setting("DescriptionHubBarHeight", 16.7F, 0.0F, 30.0F).des("Description Mode Hub Color Bar Width").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  70 */     this.descriptionModeHubBarRound = setting("DesHubBarRound", true).des("Description Mode Hub Color Bar Rounded").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  71 */     this.descriptionModeHubBarRoundRadius = setting("DesHubBarCornerRadius", 0.7F, 0.0F, 1.0F).des("Description Mode Hub Color Bar Rounded Corner Radius").whenTrue(this.descriptionModeHubBarRound).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  72 */     this.descriptionModeHubBarRoundTopRight = setting("DesHubBarRoundTopRight", true).des("Description Mode Hub Color Bar Rounded Top Right").whenTrue(this.descriptionModeHubBarRound).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  73 */     this.descriptionModeHubBarRoundTopLeft = setting("DesHubBarRoundTopLeft", true).des("Description Mode Hub Color Bar Rounded Top Left").whenTrue(this.descriptionModeHubBarRound).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  74 */     this.descriptionModeHubBarRoundBottomRight = setting("DesHubBarRoundDownRight", false).des("Description Mode Hub Color Bar Rounded Bottom Right").whenTrue(this.descriptionModeHubBarRound).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  75 */     this.descriptionModeHubBarRoundBottomLeft = setting("DesHubBarRoundBottomLeft", false).des("Description Mode Hub Color Bar Rounded Bottom Left").whenTrue(this.descriptionModeHubBarRound).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  76 */     this.descriptionModeHubBarColor = setting("DesHubBarColor", new Color((new Color(69, 0, 178, 255)).getRGB(), false, false, 1.0F, 0.75F, 0.9F, 69, 0, 178, 255)).des("Description Hub Bar Color").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Base).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*     */     
/*  78 */     this.descriptionModeHubBarGlow = setting("DesHubBarGlow", true).des("Description Hub Bar Glow").only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  79 */     this.descriptionModeHubBarGlowXOffset = setting("DesHubBarGlowX", 0.0F, -30.0F, 60.0F).des("Description Hub Bar Glow X Offset").whenTrue(this.descriptionModeHubBarGlow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  80 */     this.descriptionModeHubBarGlowYOffset = setting("DesHubBarGlowY", 0.0F, -40.0F, 40.0F).des("Description Hub Bar Glow Y Offset").whenTrue(this.descriptionModeHubBarGlow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  81 */     this.descriptionModeHubBarGlowWidth = setting("DesHubBarGlowWidth", 30.0F, 0.0F, 30.0F).des("Description Hub Bar Glow Width").whenTrue(this.descriptionModeHubBarGlow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  82 */     this.descriptionModeHubBarGlowHeight = setting("DesHubBarGlowHeight", 33.9F, 0.0F, 300.0F).des("Description Hub Bar Glow Height").whenTrue(this.descriptionModeHubBarGlow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  83 */     this.descriptionModeHubBarGlowColor = setting("DesHubBarGlowColor", new Color((new Color(120, 40, 255, 100)).getRGB(), false, false, 1.0F, 0.75F, 0.9F, 120, 40, 255, 100)).des("Description Hub Bar Glow Color").whenTrue(this.descriptionModeHubBarGlow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  84 */     this.descriptionModeHubBarTextShadow = setting("DesHubBarTextShadow", true).des("Description hub bar text gradient shadow").whenTrue(this.descriptionModeHubHeaderText).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  85 */     this.descriptionModeHubBarTextShadowWidth = setting("DesHubBarTextShadowWidth", -0.4F, -50.0F, 100.0F).des("Description hub bar text gradient shadow width").whenTrue(this.descriptionModeHubHeaderText).whenTrue(this.descriptionModeHubBarTextShadow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  86 */     this.descriptionModeHubBarTextShadowHeight = setting("DesHubBarTextShadowHeight", 0.9F, -50.0F, 50.0F).des("Description hub bar text gradient shadow height").whenTrue(this.descriptionModeHubHeaderText).whenTrue(this.descriptionModeHubBarTextShadow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  87 */     this.descriptionModeHubBarTextShadowSize = setting("DesHubBarTextShadowSize", 0.1F, 0.0F, 1.0F).des("Description hub bar text gradient shadow size").whenTrue(this.descriptionModeHubHeaderText).whenTrue(this.descriptionModeHubBarTextShadow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  88 */     this.descriptionModeHubBarTextShadowAlpha = setting("DesHubBarTextShadowAlpha", 69, 0, 255).des("Description hub bar text gradient shadow alpha").whenTrue(this.descriptionModeHubHeaderText).whenTrue(this.descriptionModeHubBarTextShadow).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  89 */     this.descriptionModeHubBarIconBG = setting("DesHubBarIconBG", true).des("Description hub bar icon background color block").whenTrue(this.descriptionModeHubIcon).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  90 */     this.descriptionModeHubBarIconBGScaleOutside = setting("DesHubBarIconBGScale", 0.7F, 0.0F, 1.0F).des("Description hub bar icon background color block scale").whenTrue(this.descriptionModeHubIcon).whenTrue(this.descriptionModeHubBarIconBG).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  91 */     this.descriptionModeHubBarIconBGSideX = setting("DesHubBarIconBGSideX", 0.0F, -30.0F, 30.0F).des("Description hub bar icon background color block side x offset").whenTrue(this.descriptionModeHubIcon).whenTrue(this.descriptionModeHubBarIconBG).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  92 */     this.descriptionModeHubBarIconBGFade = setting("DesHubBarIconBGFade", true).des("Description hub bar icon background color block side fade").whenTrue(this.descriptionModeHubIcon).whenTrue(this.descriptionModeHubBarIconBG).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  93 */     this.descriptionModeHubBarIconBGFadeSize = setting("DesHubBarIconBGFadeSize", 31.3F, -30.0F, 70.0F).des("Description hub bar icon background color block side fade size").whenTrue(this.descriptionModeHubIcon).whenTrue(this.descriptionModeHubBarIconBGFade).whenTrue(this.descriptionModeHubBarIconBG).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*  94 */     this.descriptionModeHubBarIconBGColor = setting("DesHubBarIconBGColor", new Color((new Color(0, 0, 0, 93)).getRGB(), false, false, 1.0F, 0.75F, 0.9F, 0, 0, 0, 93)).des("Description hub bar icon background color block's color").whenTrue(this.descriptionModeHubIcon).whenTrue(this.descriptionModeHubBarIconBG).only(v -> (this.descriptionMode.getValue() == DescriptionMode.Hub && ((Boolean)this.descriptionModeHubBar.getValue()).booleanValue())).whenAtMode(this.descriptionModeHubBarPage, DescriptionModeHubBarPage.Glow).whenAtMode(this.descriptionModeHubPage, DescriptionModeHubPage.Bar).whenAtMode(this.page, Page.Description);
/*     */     instance = this;
/*     */   } public Setting<Float> descriptionModeHubDescriptionAnimationSpeed; public Setting<Integer> descriptionModeHubDescriptionXOffset; public Setting<Integer> descriptionModeHubDescriptionXBoundingOffset; public Setting<Integer> descriptionModeHubDescriptionYOffset; public Setting<Color> descriptionModeHubDescriptionColor; public Setting<Boolean> descriptionModeHubShadow; public Setting<Boolean> descriptionModeHubShadowCenterRect; public Setting<Float> descriptionModeHubShadowSize; public Setting<Integer> descriptionModeHubShadowAlpha; public Setting<Boolean> descriptionModeHubBar; public Setting<DescriptionModeHubBarPage> descriptionModeHubBarPage; public Setting<Float> descriptionModeHubBarHeight; public Setting<Boolean> descriptionModeHubBarRound; public Setting<Float> descriptionModeHubBarRoundRadius; public Setting<Boolean> descriptionModeHubBarRoundTopRight; public Setting<Boolean> descriptionModeHubBarRoundTopLeft; public Setting<Boolean> descriptionModeHubBarRoundBottomRight; public Setting<Boolean> descriptionModeHubBarRoundBottomLeft; public Setting<Color> descriptionModeHubBarColor; public Setting<Boolean> descriptionModeHubBarGlow; public Setting<Float> descriptionModeHubBarGlowXOffset; public Setting<Float> descriptionModeHubBarGlowYOffset; public Setting<Float> descriptionModeHubBarGlowWidth; public Setting<Float> descriptionModeHubBarGlowHeight; public Setting<Color> descriptionModeHubBarGlowColor; public Setting<Boolean> descriptionModeHubBarTextShadow; public Setting<Float> descriptionModeHubBarTextShadowWidth; public Setting<Float> descriptionModeHubBarTextShadowHeight; public Setting<Float> descriptionModeHubBarTextShadowSize; public Setting<Integer> descriptionModeHubBarTextShadowAlpha; public Setting<Boolean> descriptionModeHubBarIconBG; public Setting<Float> descriptionModeHubBarIconBGScaleOutside; public Setting<Float> descriptionModeHubBarIconBGSideX; public Setting<Boolean> descriptionModeHubBarIconBGFade; public Setting<Float> descriptionModeHubBarIconBGFadeSize; public Setting<Color> descriptionModeHubBarIconBGColor;
/*     */   public void onDisable() {
/*  98 */     enable();
/*     */   }
/*     */   
/*     */   enum Page {
/* 102 */     Description;
/*     */   }
/*     */   
/*     */   public enum DescriptionMode {
/* 106 */     MouseTag, Hub;
/*     */   }
/*     */   
/*     */   public enum DescriptionModeHubPage {
/* 110 */     Text, Rect, Outline, Bar, Shadow, RectInGlow;
/*     */   }
/*     */   
/*     */   public enum DescriptionModeHubDesTextFont {
/* 114 */     Comfortaa, Arial, Objectivity, Minecraft;
/*     */   }
/*     */   
/*     */   public enum DescriptionModeHubBarPage {
/* 118 */     Base, Glow, Outline;
/*     */   } }


/* Location:              C:\Users\XE\Desktop\moloch.su-b3.jar!\me\thediamondsword5\moloch\module\modules\client\MoreClickGUI.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */