/*     */ package net.spartanb312.base.gui;
/*     */ 
/*     */ import java.awt.Color;
/*     */ import me.thediamondsword5.moloch.core.common.Color;
/*     */ import net.minecraft.client.Minecraft;
/*     */ import net.minecraft.client.renderer.GlStateManager;
/*     */ import net.spartanb312.base.client.FontManager;
/*     */ import net.spartanb312.base.gui.components.ModuleButton;
/*     */ import net.spartanb312.base.module.modules.client.ClickGUI;
/*     */ import net.spartanb312.base.utils.graphics.RenderUtils2D;
/*     */ import net.spartanb312.base.utils.graphics.font.CFontRenderer;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public abstract class Component
/*     */ {
/*  18 */   public CFontRenderer font = FontManager.fontRenderer;
/*     */   public FontManager fontManager;
/*  20 */   public Minecraft mc = Minecraft.func_71410_x(); public int x;
/*     */   public int y;
/*  22 */   protected int fontColor = (new Color(255, 255, 255)).getRGB(); public int width; public int height;
/*     */   public Panel father;
/*     */   public boolean isExtended;
/*     */   public static boolean anyExpanded = false;
/*     */   public boolean expanded = false;
/*     */   public static Component instance;
/*  28 */   public static int colorMenuToggleThreader = 0;
/*     */   public static boolean isTyping = false;
/*     */   
/*     */   public Component() {
/*  32 */     instance = this;
/*     */   }
/*     */ 
/*     */   
/*     */   public abstract void render(int paramInt1, int paramInt2, float paramFloat1, float paramFloat2);
/*     */ 
/*     */   
/*     */   public abstract void bottomRender(int paramInt1, int paramInt2, boolean paramBoolean1, boolean paramBoolean2, float paramFloat);
/*     */   
/*     */   public abstract boolean mouseClicked(int paramInt1, int paramInt2, int paramInt3);
/*     */   
/*     */   public void mouseReleased(int mouseX, int mouseY, int state) {}
/*     */   
/*     */   public void keyTyped(char typedChar, int keyCode) {}
/*     */   
/*     */   public void solvePos(boolean add) {
/*  48 */     this.x = this.father.x + (add ? 5 : 0);
/*  49 */     this.y = this.father.y;
/*     */   }
/*     */ 
/*     */   
/*     */   public int getHoveredColor(int mouseX, int mouseY, int color) {
/*  54 */     if (isHovered(mouseX, mouseY)) {
/*  55 */       float[] hsbVals = new float[3];
/*  56 */       Color theColor = new Color(color);
/*  57 */       Color.RGBtoHSB(theColor.getRed(), theColor.getGreen(), theColor.getBlue(), hsbVals);
/*  58 */       float saturation = hsbVals[1] * 0.5F;
/*  59 */       return Color.getHSBColor(hsbVals[0], saturation, hsbVals[2]).getRGB();
/*  60 */     }  return color;
/*     */   }
/*     */   
/*     */   public boolean isHovered(int mouseX, int mouseY) {
/*  64 */     return (mouseX >= Math.min(this.x, this.x + this.width) && mouseX <= Math.max(this.x, this.x + this.width) && mouseY >= Math.min(this.y, this.y + this.height) && mouseY <= Math.max(this.y, this.y + this.height));
/*     */   }
/*     */   
/*     */   public boolean isVisible() {
/*  68 */     return true;
/*     */   }
/*     */   
/*     */   public abstract String getDescription();
/*     */   
/*     */   private void moduleSeparators(boolean isColorPanel) {
/*  74 */     GlStateManager.func_179118_c();
/*     */     
/*  76 */     if (ClickGUI.instance.moduleSeparatorFadeMode.getValue() == ClickGUI.ModuleSeparatorFadeMode.Left) {
/*  77 */       if (((Boolean)ClickGUI.instance.moduleSeparatorGlow.getValue()).booleanValue()) {
/*  78 */         GlStateManager.func_179118_c();
/*  79 */         RenderUtils2D.drawCustomRect((this.x + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) - ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), this.x + (this.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB());
/*  80 */         RenderUtils2D.drawCustomRect(this.x + (this.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) - ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), (this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() - ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/*     */         
/*  82 */         RenderUtils2D.drawCustomRect((this.x + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), this.x + (this.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) + ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/*  83 */         RenderUtils2D.drawCustomRect(this.x + (this.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() - ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) + ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/*  84 */         GlStateManager.func_179141_d();
/*     */       } 
/*  86 */       RenderUtils2D.drawCustomLine((this.x + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), this.x + (this.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), ((Integer)ClickGUI.instance.moduleSeparatorHeight.getValue()).intValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor());
/*  87 */       RenderUtils2D.drawCustomLine(this.x + (this.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() - ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), ((Integer)ClickGUI.instance.moduleSeparatorHeight.getValue()).intValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor(), (new Color(0, 0, 0, 0)).getRGB());
/*     */     }
/*  89 */     else if (ClickGUI.instance.moduleSeparatorFadeMode.getValue() == ClickGUI.ModuleSeparatorFadeMode.Right) {
/*  90 */       if (((Boolean)ClickGUI.instance.moduleSeparatorGlow.getValue()).booleanValue()) {
/*  91 */         GlStateManager.func_179118_c();
/*  92 */         RenderUtils2D.drawCustomRect((this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) - ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), (this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()) - (this.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB());
/*  93 */         RenderUtils2D.drawCustomRect((this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()) - (instance.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) - ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), (this.x + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() + ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/*     */         
/*  95 */         RenderUtils2D.drawCustomRect((this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()) - (this.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) + ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/*  96 */         RenderUtils2D.drawCustomRect((this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()) - (instance.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() + ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) + ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/*  97 */         GlStateManager.func_179141_d();
/*     */       } 
/*  99 */       RenderUtils2D.drawCustomLine((this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()) - (this.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), ((Integer)ClickGUI.instance.moduleSeparatorHeight.getValue()).intValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor());
/* 100 */       RenderUtils2D.drawCustomLine((this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()) - (instance.width - 1) * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() + ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), ((Integer)ClickGUI.instance.moduleSeparatorHeight.getValue()).intValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor(), (new Color(0, 0, 0, 0)).getRGB());
/*     */     }
/* 102 */     else if (ClickGUI.instance.moduleSeparatorFadeMode.getValue() == ClickGUI.ModuleSeparatorFadeMode.Both) {
/* 103 */       if (((Boolean)ClickGUI.instance.moduleSeparatorGlow.getValue()).booleanValue()) {
/* 104 */         GlStateManager.func_179118_c();
/* 105 */         RenderUtils2D.drawCustomRect((this.x + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() + ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) - ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), this.x + (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB());
/* 106 */         RenderUtils2D.drawCustomRect((this.x + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() + ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), this.x + (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) + ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/*     */         
/* 108 */         RenderUtils2D.drawCustomRect(this.x + (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) - ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), (this.x + this.width - 1) - (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB());
/* 109 */         RenderUtils2D.drawCustomRect(this.x + (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1) - (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) + ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/*     */         
/* 111 */         RenderUtils2D.drawCustomRect((this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() - ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) - ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), (this.x + this.width - 1) - (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB());
/* 112 */         RenderUtils2D.drawCustomRect((this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() - ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1) - (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) + ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/* 113 */         GlStateManager.func_179141_d();
/*     */       } 
/* 115 */       RenderUtils2D.drawCustomLine((this.x + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() + ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), this.x + (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), ((Integer)ClickGUI.instance.moduleSeparatorHeight.getValue()).intValue(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor());
/* 116 */       RenderUtils2D.drawCustomLine(this.x + (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1) - (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), ((Integer)ClickGUI.instance.moduleSeparatorHeight.getValue()).intValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor());
/* 117 */       RenderUtils2D.drawCustomLine((this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue() - ((Integer)ClickGUI.instance.moduleSeparatorWidth.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1) - (this.width - 1) / 2.0F * ((Float)ClickGUI.instance.moduleSeparatorFadeLength.getValue()).floatValue() + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue(), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), ((Integer)ClickGUI.instance.moduleSeparatorHeight.getValue()).intValue(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor());
/*     */     } 
/* 119 */     GlStateManager.func_179141_d();
/* 120 */     if (ClickGUI.instance.moduleSeparatorFadeMode.getValue() == ClickGUI.ModuleSeparatorFadeMode.None) {
/* 121 */       if (((Boolean)ClickGUI.instance.moduleSeparatorGlow.getValue()).booleanValue()) {
/* 122 */         GlStateManager.func_179118_c();
/* 123 */         RenderUtils2D.drawCustomRect(this.x, (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) - ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), (this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB());
/* 124 */         RenderUtils2D.drawCustomRect(this.x, (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()) + ((Float)ClickGUI.instance.moduleSeparatorGlowHeight.getValue()).floatValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSeparatorGlowAlpha.getValue()).intValue())).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB());
/* 125 */         GlStateManager.func_179141_d();
/*     */       } 
/* 127 */       RenderUtils2D.drawCustomLine(this.x, (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), (this.x + this.width - 1 + ((Integer)ClickGUI.instance.moduleSeparatorX.getValue()).intValue()), (this.y + this.height + ((Integer)ClickGUI.instance.moduleSeparatorY.getValue()).intValue()), ((Integer)ClickGUI.instance.moduleSeparatorHeight.getValue()).intValue(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor(), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSeparatorColor.getValue()).getColor());
/*     */     } 
/*     */   }
/*     */   
/*     */   private void panelSideGlow(boolean isColorPanel) {
/* 132 */     if (ClickGUI.instance.moduleSideGlow.getValue() != ClickGUI.ModuleSideGlow.None) {
/* 133 */       GlStateManager.func_179118_c();
/* 134 */       int panelSideGlowColor = isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColor();
/* 135 */       if (ClickGUI.instance.moduleSideGlow.getValue() == ClickGUI.ModuleSideGlow.Left || ClickGUI.instance.moduleSideGlow.getValue() == ClickGUI.ModuleSideGlow.Both) {
/* 136 */         RenderUtils2D.drawCustomRect(this.x, this.y, this.x + ((Float)ClickGUI.instance.moduleSideGlowWidth.getValue()).floatValue(), (this.y + this.height), (new Color(0, 0, 0, 0)).getRGB(), panelSideGlowColor, panelSideGlowColor, (new Color(0, 0, 0, 0)).getRGB());
/*     */       }
/* 138 */       if (ClickGUI.instance.moduleSideGlow.getValue() == ClickGUI.ModuleSideGlow.Right || ClickGUI.instance.moduleSideGlow.getValue() == ClickGUI.ModuleSideGlow.Both) {
/* 139 */         RenderUtils2D.drawCustomRect((this.x + this.width) - ((Float)ClickGUI.instance.moduleSideGlowWidth.getValue()).floatValue(), this.y, (this.x + this.width), (this.y + this.height), panelSideGlowColor, (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), panelSideGlowColor);
/*     */       }
/* 141 */       GlStateManager.func_179141_d();
/*     */     } 
/*     */   }
/*     */   
/*     */   public void drawSettingRects(boolean lastSetting, boolean isColorPanel) {
/* 146 */     if (!((Boolean)ClickGUI.instance.moduleSideGlowLayer.getValue()).booleanValue()) {
/* 147 */       panelSideGlow(isColorPanel);
/*     */     }
/* 149 */     if (((Boolean)ClickGUI.instance.moduleSeparators.getValue()).booleanValue() && !((Boolean)ClickGUI.instance.moduleSeparatorsOnTop.getValue()).booleanValue() && !lastSetting) {
/* 150 */       moduleSeparators(isColorPanel);
/*     */     }
/*     */     
/* 153 */     RenderUtils2D.drawRect(this.x, this.y, (this.x + this.width), (this.y + this.height), isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleBGColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleBGColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleBGColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.moduleBGColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.moduleBGColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.moduleBGColor.getValue()).getColor());
/* 154 */     RenderUtils2D.drawRect((this.x + 1), (this.y + 1), (this.x + this.width - 1), (this.y + this.height - ((Integer)ClickGUI.instance.extendedRectGap.getValue()).intValue()), isColorPanel ? (new Color(((Color)ClickGUI.instance.extendedRectColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.extendedRectColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.extendedRectColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.extendedRectColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.extendedRectColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.extendedRectColor.getValue()).getColor());
/*     */     
/* 156 */     if (((Boolean)ClickGUI.instance.moduleSideGlowLayer.getValue()).booleanValue()) {
/* 157 */       panelSideGlow(isColorPanel);
/*     */     }
/* 159 */     if (ClickGUI.instance.moduleSideGlow.getValue() != ClickGUI.ModuleSideGlow.None) {
/* 160 */       GlStateManager.func_179118_c();
/* 161 */       int panelSideGlowDoubleColor = isColorPanel ? (new Color(((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Integer)ClickGUI.instance.moduleSideGlowDoubleAlpha.getValue()).intValue() / 300.0F * colorMenuToggleThreader) : ((Integer)ClickGUI.instance.moduleSideGlowDoubleAlpha.getValue()).intValue())).getRGB() : (new Color(((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.moduleSideGlowColor.getValue()).getColorColor().getBlue(), ((Integer)ClickGUI.instance.moduleSideGlowDoubleAlpha.getValue()).intValue())).getRGB();
/* 162 */       if (ClickGUI.instance.moduleSideGlowDouble.getValue() == ClickGUI.ModuleSideGlowDouble.Left) {
/* 163 */         RenderUtils2D.drawCustomRect(this.x, this.y, this.x + ((Float)ClickGUI.instance.moduleSideGlowDoubleWidth.getValue()).floatValue(), (this.y + this.height), (new Color(0, 0, 0, 0)).getRGB(), panelSideGlowDoubleColor, panelSideGlowDoubleColor, (new Color(0, 0, 0, 0)).getRGB());
/*     */       }
/* 165 */       else if (ClickGUI.instance.moduleSideGlowDouble.getValue() == ClickGUI.ModuleSideGlowDouble.Right) {
/* 166 */         RenderUtils2D.drawCustomRect((this.x + this.width) - ((Float)ClickGUI.instance.moduleSideGlowDoubleWidth.getValue()).floatValue(), this.y, (this.x + this.width), (this.y + this.height), panelSideGlowDoubleColor, (new Color(0, 0, 0, 0)).getRGB(), (new Color(0, 0, 0, 0)).getRGB(), panelSideGlowDoubleColor);
/*     */       } 
/* 168 */       GlStateManager.func_179141_d();
/*     */     } 
/*     */     
/* 171 */     if (((Boolean)ClickGUI.instance.moduleSeparators.getValue()).booleanValue() && ((Boolean)ClickGUI.instance.moduleSeparatorsOnTop.getValue()).booleanValue() && !lastSetting) {
/* 172 */       moduleSeparators(isColorPanel);
/*     */     }
/*     */   }
/*     */   
/*     */   public void renderHoverRect(String key, int mouseX, int mouseY, float yTopOffset, float yDownOffset, boolean moduleGap) {
/* 177 */     if (((Boolean)ClickGUI.instance.moduleHoverStuff.getValue()).booleanValue()) {
/* 178 */       ModuleButton.storedHovered.putIfAbsent(key, Integer.valueOf(0));
/* 179 */       ModuleButton.storedHoverScaleLoops.putIfAbsent(key, Float.valueOf(0.0F));
/* 180 */       if (isHovered(mouseX, mouseY)) {
/* 181 */         ModuleButton.storedHovered.put(key, ClickGUI.instance.moduleHoverFadeFactor.getValue());
/* 182 */         if (ClickGUI.instance.moduleHoverScaleFade.getValue() != ClickGUI.HoverScaleFadeMode.None) {
/* 183 */           ModuleButton.storedHoverScaleLoops.put(key, Float.valueOf(300.0F));
/*     */         }
/*     */       } 
/* 186 */       if (ModuleButton.storedHovered.containsKey(key)) {
/* 187 */         int hoverLoops = ((Integer)ModuleButton.storedHovered.get(key)).intValue();
/* 188 */         float hoverScaleLoops = ((Float)ModuleButton.storedHoverScaleLoops.get(key)).floatValue();
/* 189 */         int hoverAlpha = (int)(((Integer)ClickGUI.instance.moduleHoverStartAlpha.getValue()).intValue() * hoverLoops / ((Integer)ClickGUI.instance.moduleHoverFadeFactor.getValue()).intValue());
/* 190 */         if (hoverAlpha < 0) {
/* 191 */           hoverAlpha = 0;
/*     */         }
/* 193 */         if (hoverScaleLoops < 0.0F) {
/* 194 */           hoverScaleLoops = 0.0F;
/*     */         }
/* 196 */         GlStateManager.func_179118_c();
/* 197 */         Color hoveredRectColor = new Color(((Color)ClickGUI.instance.enabledColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.enabledColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.enabledColor.getValue()).getColorColor().getBlue(), ((Color)ClickGUI.instance.enabledColor.getValue()).getAlpha());
/* 198 */         RenderUtils2D.drawRect((ClickGUI.instance.moduleHoverScaleFade.getValue() == ClickGUI.HoverScaleFadeMode.Right || ClickGUI.instance.moduleHoverScaleFade.getValue() == ClickGUI.HoverScaleFadeMode.Both || ClickGUI.instance.moduleHoverScaleFade.getValue() == ClickGUI.HoverScaleFadeMode.All) ? ((this.x + 1 + instance.width - 1) - hoverScaleLoops * (instance.width - 1) / 300.0F) : (this.x + 1), (ClickGUI.instance.moduleHoverScaleFade.getValue() == ClickGUI.HoverScaleFadeMode.All) ? ((this.y - 1) + yTopOffset + instance.height - hoverScaleLoops * instance.height / 300.0F) : ((this.y - 1) + yTopOffset), (ClickGUI.instance.moduleHoverScaleFade.getValue() == ClickGUI.HoverScaleFadeMode.Left || ClickGUI.instance.moduleHoverScaleFade.getValue() == ClickGUI.HoverScaleFadeMode.Both || ClickGUI.instance.moduleHoverScaleFade.getValue() == ClickGUI.HoverScaleFadeMode.All) ? ((this.x + 1) + hoverScaleLoops * (instance.width - 1) / 300.0F) : (this.x + instance.width - 1), (ClickGUI.instance.moduleHoverScaleFade.getValue() == ClickGUI.HoverScaleFadeMode.All) ? (this.y - yDownOffset + hoverScaleLoops * instance.height / 300.0F - (moduleGap ? ((Integer)ClickGUI.instance.moduleGap.getValue()).intValue() : false)) : ((this.y + instance.height) - yDownOffset - (moduleGap ? ((Integer)ClickGUI.instance.moduleGap.getValue()).intValue() : false)), (new Color(hoveredRectColor.getRed(), hoveredRectColor.getGreen(), hoveredRectColor.getBlue(), hoverAlpha)).getRGB());
/* 199 */         GlStateManager.func_179141_d();
/* 200 */         hoverLoops--;
/* 201 */         ModuleButton.storedHovered.put(key, Integer.valueOf(hoverLoops));
/*     */         
/* 203 */         hoverScaleLoops -= hoverScaleLoops / (100.0F - ((Float)ClickGUI.instance.moduleHoverScaleFadeFactor.getValue()).floatValue());
/* 204 */         ModuleButton.storedHoverScaleLoops.put(key, Float.valueOf(hoverScaleLoops));
/*     */         
/* 206 */         if (((Integer)ModuleButton.storedHovered.get(key)).intValue() <= 0) {
/* 207 */           ModuleButton.storedHovered.remove(key);
/*     */         }
/*     */       } 
/*     */     } 
/*     */   }
/*     */   
/*     */   public void drawExtendedLine(boolean lastSetting) {
/* 214 */     RenderUtils2D.drawCustomLine(this.x + ((Float)ClickGUI.instance.extendedWidth.getValue()).floatValue() / 2.0F, this.y, this.x + ((Float)ClickGUI.instance.extendedWidth.getValue()).floatValue() / 2.0F, (this.y + this.height - ((lastSetting && !((Boolean)ClickGUI.instance.extendedBottomExtensions.getValue()).booleanValue()) ? 1 : 0)), ((Float)ClickGUI.instance.extendedWidth.getValue()).floatValue(), ((Color)ClickGUI.instance.extendedColor.getValue()).getColor(), ((Color)ClickGUI.instance.extendedColor.getValue()).getColor());
/*     */   }
/*     */   
/*     */   public void drawExtendedLineColor(boolean lastSetting) {
/* 218 */     int extendedLineColorColor = (new Color(((Color)ClickGUI.instance.colorDropMenuSideBarColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.colorDropMenuSideBarColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.colorDropMenuSideBarColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.colorDropMenuSideBarColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.colorDropMenuSideBarColor.getValue()).getAlpha())).getRGB();
/* 219 */     RenderUtils2D.drawCustomLine(this.x + ((Float)ClickGUI.instance.colorDropMenuSideBarWidth.getValue()).floatValue() / 2.0F, this.y, this.x + ((Float)ClickGUI.instance.colorDropMenuSideBarWidth.getValue()).floatValue() / 2.0F, (this.y + this.height - ((lastSetting && !((Boolean)ClickGUI.instance.colorDropMenuExtensions.getValue()).booleanValue()) ? 1 : 0)), ((Float)ClickGUI.instance.colorDropMenuSideBarWidth.getValue()).floatValue(), extendedLineColorColor, extendedLineColorColor);
/*     */   }
/*     */   
/*     */   public void drawColorMenuOutline(boolean lastSetting, boolean firstSetting, boolean isExtensionsOn) {
/* 223 */     int colorMenuOutlineColor = (new Color(((Color)ClickGUI.instance.colorDropMenuOutlineColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.colorDropMenuOutlineColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.colorDropMenuOutlineColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.colorDropMenuOutlineColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.colorDropMenuOutlineColor.getValue()).getAlpha())).getRGB();
/* 224 */     RenderUtils2D.drawCustomLine(this.x + ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue() / 2.0F, this.y, this.x + ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue() / 2.0F, (this.y + this.height - ((lastSetting && !((Boolean)ClickGUI.instance.colorDropMenuExtensions.getValue()).booleanValue()) ? 1 : 0)), ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue(), colorMenuOutlineColor, colorMenuOutlineColor);
/* 225 */     RenderUtils2D.drawCustomLine((this.x + this.width) - ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue() / 2.0F, this.y, (this.x + this.width) - ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue() / 2.0F, (this.y + this.height - ((lastSetting && !((Boolean)ClickGUI.instance.colorDropMenuExtensions.getValue()).booleanValue()) ? 1 : 0)), ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue(), ((Color)ClickGUI.instance.colorDropMenuOutlineColor.getValue()).getColor(), ((Color)ClickGUI.instance.colorDropMenuOutlineColor.getValue()).getColor());
/* 226 */     if (!isExtensionsOn) {
/* 227 */       if (firstSetting) {
/* 228 */         RenderUtils2D.drawCustomLine(this.x + ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue() / 2.0F, this.y, (this.x + this.width) - ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue() / 2.0F, this.y, ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue(), colorMenuOutlineColor, colorMenuOutlineColor);
/*     */       }
/* 230 */       if (lastSetting) {
/* 231 */         RenderUtils2D.drawCustomLine(this.x + ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue() / 2.0F, (this.y + this.height), (this.x + this.width) - ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue() / 2.0F, (this.y + this.height), ((Float)ClickGUI.instance.colorDropMenuOutlineWidth.getValue()).floatValue(), colorMenuOutlineColor, colorMenuOutlineColor);
/*     */       }
/*     */     } 
/*     */   }
/*     */   
/*     */   public void drawExtendedGradient(boolean lastSetting, boolean isColorPanel) {
/* 237 */     int extendedGradientColor = isColorPanel ? (new Color(((Color)ClickGUI.instance.extendedGradientColor.getValue()).getColorColor().getRed(), ((Color)ClickGUI.instance.extendedGradientColor.getValue()).getColorColor().getGreen(), ((Color)ClickGUI.instance.extendedGradientColor.getValue()).getColorColor().getBlue(), ((Boolean)ClickGUI.instance.colorDropMenuAnimate.getValue()).booleanValue() ? (int)(((Color)ClickGUI.instance.extendedGradientColor.getValue()).getAlpha() / 300.0F * colorMenuToggleThreader) : ((Color)ClickGUI.instance.extendedGradientColor.getValue()).getAlpha())).getRGB() : ((Color)ClickGUI.instance.extendedGradientColor.getValue()).getColor();
/* 238 */     if (((Boolean)ClickGUI.instance.extendedVerticalGradient.getValue()).booleanValue()) {
/* 239 */       GlStateManager.func_179118_c();
/* 240 */       RenderUtils2D.drawCustomRect(this.x, this.y, this.x + ((Float)ClickGUI.instance.extendedGradientWidth.getValue()).floatValue(), (this.y + this.height - ((lastSetting && !((Boolean)ClickGUI.instance.extendedBottomExtensions.getValue()).booleanValue()) ? 1 : 0)), (new Color(0, 0, 0, 0)).getRGB(), extendedGradientColor, extendedGradientColor, (new Color(0, 0, 0, 0)).getRGB());
/* 241 */       GlStateManager.func_179141_d();
/*     */     } 
/*     */   }
/*     */ }


/* Location:              C:\Users\XE\Desktop\moloch.su-b3.jar!\net\spartanb312\base\gui\Component.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */